version: "3.8"
services:
  app:
    build: ./backend
    volumes:
      - ./backend:/django
    ports:
      - "8000:8000"
    image: app:django
    container_name: django_container
    depends_on:
      - db
  db:
    build: ./backend/mariaDB
    restart: always
    volumes:
      - ./backend/data/mysql/db:/var/lib/mysql
