version: "3.8"
services:
  app:
    build: .
    volumes:
      - .:/django
    ports:
      - "8000:8000"
    image: app:django
    container_name: django_container
    depends_on:
      - db
  db:
    build: ./mariaDB
    restart: always
    volumes:
      - ./data/mysql/db:/var/lib/mysql
