version: "3.9"
volumes:
  data:
services:
  db:
    image: cytopia/mariadb-5.5
    environment:
      - MYSQL_ROOT_PASSWORD=mypass
      - MYSQL_ROOT_HOST=%
    volumes:
      - data:/var/lib/mysql
    ports:
      - "3306:3306"
